### ISSUE TITLE
In android phones that have previous versions installed, secrets list is cleared when you add a secret

### ISSUE THREAD

**Issue by confraria** [nearform/optic-expo#758] opened 2022-10-06 09:59 UTC
Only in published version in google play. (version 1.0.7)

When a secret is added via QR code or manually the list of secrets is always cleared, either manually or via QR code.
When you start with an empty list it always stays empty.
Importing an [unencrypted list of secrets](https://github.com/nearform/optic-expo/files/9723781/optic-exported-secrets-unencrypted.txt) seems to work but disappears both when you try to add a secret and re-login.

In expo version the problem is not visible, and neither it was in the internal testing version.

using `adb logcat | grep ReactNativeJS` while running the app in a phone connected to the laptop we can see the error:

`10-06 11:09:51.018 14365 14432 E ReactNativeJS: 'Failed to upsert secret into data store', [Error: Could not encrypt/decrypt the value for SecureStore]`

with further inspection this seems to be root error:

```
10-06 11:33:43.799 18151 24448 W ExpoSecureStore: javax.crypto.AEADBadTagException
10-06 11:33:43.799 18151 24448 W ExpoSecureStore: 	at android.security.keystore.AndroidKeyStoreCipherSpiBase.engineDoFinal(AndroidKeyStoreCipherSpiBase.java:517)
10-06 11:33:43.799 18151 24448 W ExpoSecureStore: 	at javax.crypto.Cipher.doFinal(Cipher.java:2055)
10-06 11:33:43.799 18151 24448 W ExpoSecureStore: 	at expo.modules.securestore.SecureStoreModule$AESEncrypter.lambda$decryptItem$1(SecureStoreModule.java:466)
10-06 11:33:43.799 18151 24448 W ExpoSecureStore: 	at expo.modules.securestore.SecureStoreModule$AESEncrypter$$ExternalSyntheticLambda1.run(Unknown Source:2)
10-06 11:33:43.799 18151 24448 W ExpoSecureStore: 	at expo.modules.securestore.AuthenticationHelper.handleEncryptionCallback(AuthenticationHelper.kt:86)
10-06 11:33:43.799 18151 24448 W ExpoSecureStore: 	at expo.modules.securestore.AuthenticationHelper$defaultCallback$1.checkAuthentication(AuthenticationHelper.kt:73)
10-06 11:33:43.799 18151 24448 W ExpoSecureStore: 	at expo.modules.securestore.SecureStoreModule$AESEncrypter.decryptItem(SecureStoreModule.java:464)
10-06 11:33:43.799 18151 24448 W ExpoSecureStore: 	at expo.modules.securestore.SecureStoreModule.readJSONEncodedItem(SecureStoreModule.java:205)
10-06 11:33:43.799 18151 24448 W ExpoSecureStore: 	at expo.modules.securestore.SecureStoreModule.getItemImpl(SecureStoreModule.java:177)
10-06 11:33:43.799 18151 24448 W ExpoSecureStore: 	at expo.modules.securestore.SecureStoreModule.getValueWithKeyAsync(SecureStoreModule.java:165)
10-06 11:33:43.799 18151 24448 W ExpoSecureStore: 	at java.lang.reflect.Method.invoke(Native Method)
10-06 11:33:43.799 18151 24448 W ExpoSecureStore: 	at expo.modules.core.ExportedModule.invokeExportedMethod(ExportedModule.java:98)
10-06 11:33:43.799 18151 24448 W ExpoSecureStore: 	at expo.modules.adapters.react.NativeModulesProxy.callMethod(NativeModulesProxy.java:162)
10-06 11:33:43.799 18151 24448 W ExpoSecureStore: 	at java.lang.reflect.Method.invoke(Native Method)
10-06 11:33:43.799 18151 24448 W ExpoSecureStore: 	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
10-06 11:33:43.799 18151 24448 W ExpoSecureStore: 	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:188)
10-06 11:33:43.799 18151 24448 W ExpoSecureStore: 	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
10-06 11:33:43.799 18151 24448 W ExpoSecureStore: 	at android.os.Handler.handleCallback(Handler.java:938)
10-06 11:33:43.799 18151 24448 W ExpoSecureStore: 	at android.os.Handler.dispatchMessage(Handler.java:99)
10-06 11:33:43.799 18151 24448 W ExpoSecureStore: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
10-06 11:33:43.799 18151 24448 W ExpoSecureStore: 	at android.os.Looper.loop(Looper.java:237)
10-06 11:33:43.799 18151 24448 W ExpoSecureStore: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:228)
10-06 11:33:43.799 18151 24448 W ExpoSecureStore: 	at java.lang.Thread.run(Thread.java:923)
10-06 11:33:43.799 18151 24448 W ExpoSecureStore: Caused by: android.security.KeyStoreException: Signature/MAC verification failed
10-06 11:33:43.799 18151 24448 W ExpoSecureStore: 	at android.security.KeyStore.getKeyStoreException(KeyStore.java:1301)
10-06 11:33:43.799 18151 24448 W ExpoSecureStore: 	at android.security.keystore.KeyStoreCryptoOperationChunkedStreamer.doFinal(KeyStoreCryptoOperationChunkedStreamer.java:186)
10-06 11:33:43.799 18151 24448 W ExpoSecureStore: 	at android.security.keystore.AndroidKeyStoreAuthenticatedAESCipherSpi$BufferAllOutputUntilDoFinalStreamer.doFinal(AndroidKeyStoreAuthenticatedAESCipherSpi.java:373)
10-06 11:33:43.799 18151 24448 W ExpoSecureStore: 	at android.security.keystore.AndroidKeyStoreCipherSpiBase.engineDoFinal(AndroidKeyStoreCipherSpiBase.java:506)
10-06 11:33:43.799 18151 24448 W ExpoSecureStore: 	... 22 more
```

**Comment by confraria** [comment] 2022-10-06 15:25
this only happens in phones that had previous versions installed (which was the case with the 2 android devices I have with me).

😅 which makes much less serious than I thought at first

**Comment by simoneb** [comment] 2022-10-11 15:32
I'm going to close this issue as I guess this is a temporary one caused by an initial version of the app published. @confraria let me know if I'm understanding this wrong though, this won't happen for future versions right, as long as nobody had installed version 1.0.7 before?

**Comment by confraria** [comment] 2022-10-11 17:58
@simoneb that's right. so far I'm the only one affected by this . From my understanding this won't happen to future versions.

**Closed** 2022-10-11 22:59 UTC
