### ISSUE TITLE
App crashing when showing old notifcations

### ISSUE THREAD

**Issue by guilhermelimak** [nearform/optic-expo#846] opened 2022-11-16 21:06 UTC
There's a bug where old notifications cause the app to crash when opening the notifications screen.
Here's a video of the bug happening in the native version of the app (the OTP requests that should appear on the page were made yesterday):

https://user-images.githubusercontent.com/6863574/202291902-6beb135b-8d54-49c8-8f5a-cbd5ede57e37.mp4

After some time investigating I wasn't able to find the exact cause or how to reproduce the issue consistently. It did however happened in Expo Go once while I was developing another feature so I was able to take a look at the error, which was both `secret` and `token` where undefined [here](https://github.com/nearform/optic-expo/blob/72d5d887c481bb676ad629538ced92e0c79399d6/src/components/NotificationCard.tsx#L98-L99) causing the subsequent [`secret.secret`](https://github.com/nearform/optic-expo/blob/72d5d887c481bb676ad629538ced92e0c79399d6/src/components/NotificationCard.tsx#L118) and [`token.token`](https://github.com/nearform/optic-expo/blob/72d5d887c481bb676ad629538ced92e0c79399d6/src/components/NotificationCard.tsx#L153) references to throw a `Cannot access property of undefined` error.

**Comment by simoneb** [comment] 2022-11-16 21:43
Can you describe a repro? I'm not sure how you even get to an old notification!

**Comment by guilhermelimak** [comment] 2022-11-16 21:45
> Can you describe a repro? I'm not sure how you even get to an old notification!

I'm not really sure how to reproduce as I mentioned. What I meant by old notification was just a request that was sent yesterday but wasn't approved/dismissed.

**Comment by brunopascottini** [comment] 2022-11-23 10:56
I tested in my iOS device using the development build and the production build from the `App Store` and noticed that if push notifications are not allowed, the app doesn't work as expected when executing some actions that trigger notifications as adding tokens, even the toast related to error handling is hidden behind the keyboard. 
It works as expected as soon as I re-enable push notifications in the settings.
The app did not crash at any moment for me, as in the video you shared. Also, I didn't get any notifications in the specified tab.
@guilhermelimak Could you please test if the same happens to you? It may not be related to this issue but if you can reproduce it as well I'll create an issue to look further into this.

**Comment by simoneb** [comment] 2022-11-23 11:10
@brunopascottini I think what you tested is something different, although a possible issue as well. On the other hand there isn't much of a point in using this app without enabling push notifications. I believe Guilherme can't reproduce this issue either, and I've never come across it myself. Hence, lacking the ability to reproduce it consistently, I'd just close it.

**Closed** 2022-11-23 11:17 UTC
Labels: bug
