### ISSUE TITLE
Stale UI state on second login

### ISSUE THREAD

**Issue by richiemccoll** [nearform/optic-expo#17] opened 2021-02-17 15:58 UTC
**UPDATE**: the PR which fixes this issue has been merged but it needs an expo SDK release to be available. See https://github.com/expo/expo/pull/11503

I noticed some stale UI state after logging in with Google. This only happens after I log in and logout once. I was able to reproduce it on both iPhone and Android.

https://user-images.githubusercontent.com/12698531/108235942-471e2100-713e-11eb-84d4-d1309478cc81.MP4

## Steps to Reproduce
- Login with Google & logout
- Login again with the same account

## Expected
- User arrives on the Home screen

## Actual
- User is stuck on the Auth screen

**Comment by simoneb** [comment] 2021-02-17 16:09
it works for me

**Comment by richiemccoll** [comment] 2021-02-17 16:38
@simoneb I've updated the PR description with a screen recording to illustrate the bug.

**Comment by simoneb** [comment] 2021-02-17 21:01
I tried the steps but could not reproduce it. Let's sync on this tomorrow.

**Comment by n370** [comment] 2021-03-02 00:46
Seem like we have company here. I've tried the changes seen at https://github.com/expo/expo/issues/11714#issuecomment-765688023 and was able to get a consistent behavior where the login would work every other way.

There is a change coming that may get this one fixed for us: https://github.com/expo/expo/pull/11503#pullrequestreview-599869903.

**Comment by simoneb** [comment] 2021-03-02 07:36
Good catch!

**Comment by tiagoheliob** [comment] 2021-09-28 17:23
Issued was fixed on this PR https://github.com/expo/expo/pull/11503

**Comment by simoneb** [comment] 2021-09-29 07:50
@tiagoheliob the issue was fixed in expo but did you check if we're using the expo version which includes that fix? Because I don't think we updated expo since a long time, hence the fix is not in the version we're using here. I'm reopening the issue, if you want to close it can you please double check this?

**Comment by simoneb** [comment] 2021-09-29 07:51
I've also created https://github.com/nearform/optic-expo/issues/153 to upgrade expo to latest

**Comment by simoneb** [comment] 2021-10-01 16:14
We need to verify whether this is still an issue after the application underwent further changes and after the expo upgrade, which may have got us the fix.

**Comment by salmanm** [comment] 2021-10-22 04:00
Looks like this is fixed now. I tried logging in/out and all seemed fine on my phone

**Closed by salmanm** 2021-10-22 04:00 UTC
Labels: bug
